version: '3.8'

services:
  coursework2aspnetserver:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}coursework2aspnetserver
    build:
      context: .
      dockerfile: CourseWork2AspNetServer/Dockerfile
    restart: always
    links: 
      - "db:database"
    ports:
      - "80:80"
      #- "443:443"
    #ports:
    ## Replace the values on the left by the values on your launchSettings.json
    #  - "51217:80"
    #  - "44349:443"
    #environment:
    #  ASPNETCORE_ENVIRONMENT: "Development"
    #  ASPNETCORE_URLS: "https://+;http://+"
    #  ASPNETCORE_HTTPS_PORT: "44349"
    #volumes:
    #  - "${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets"
    #  - "${HOME}/.aspnet/https:/root/.aspnet/https/"
  
  db:
    image: postgres
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    external: true
